repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
    - id: black
- repo: https://github.com/astral-sh/ruff-pre-commit.git
  rev: v0.0.292
  hooks:
    - id: ruff
      exclude: ^instance/settings|migrations/
      args: [--fix, --exit-non-zero-on-fix]
- repo: https://github.com/PyCQA/docformatter.git
  rev: v1.5.1
  hooks:
    - id: docformatter
